/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ApiCompileRouteImport } from './routes/api/compile'
import { Route as PreviewIdRouteImport } from './routes/preview.$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as ApiAgentsAttachmentRouteImport } from './routes/api/agents/attachment'
import { Route as ApiAgentsDeleteRouteImport } from './routes/api/agents/delete'
import { Route as ApiAgentsSendRouteImport } from './routes/api/agents/send'
import { Route as ApiAgentsSpawnRouteImport } from './routes/api/agents/spawn'
import { Route as ApiAgentsStopRouteImport } from './routes/api/agents/stop'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDataTxRouteImport } from './routes/api/data/tx'
import { Route as ApiDataProjectsIndexRouteImport } from './routes/api/data/projects/index'
import { Route as ApiDataProjectsIdRouteImport } from './routes/api/data/projects/$id'
import { Route as ApiDataProjectsDuplicateRouteImport } from './routes/api/data/projects/duplicate'
import { Route as ApiDataProjectsRemoveRouteImport } from './routes/api/data/projects/remove'
import { Route as ApiDataProjectsSetPublicRouteImport } from './routes/api/data/projects/set-public'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompileRoute = ApiCompileRouteImport.update({
  id: '/api/compile',
  path: '/api/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIdRoute = PreviewIdRouteImport.update({
  id: '/preview/$id',
  path: '/preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsAttachmentRoute = ApiAgentsAttachmentRouteImport.update({
  id: '/api/agents/attachment',
  path: '/api/agents/attachment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsDeleteRoute = ApiAgentsDeleteRouteImport.update({
  id: '/api/agents/delete',
  path: '/api/agents/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsSendRoute = ApiAgentsSendRouteImport.update({
  id: '/api/agents/send',
  path: '/api/agents/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsSpawnRoute = ApiAgentsSpawnRouteImport.update({
  id: '/api/agents/spawn',
  path: '/api/agents/spawn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsStopRoute = ApiAgentsStopRouteImport.update({
  id: '/api/agents/stop',
  path: '/api/agents/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataTxRoute = ApiDataTxRouteImport.update({
  id: '/api/data/tx',
  path: '/api/data/tx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataProjectsIndexRoute = ApiDataProjectsIndexRouteImport.update({
  id: '/api/data/projects/',
  path: '/api/data/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataProjectsIdRoute = ApiDataProjectsIdRouteImport.update({
  id: '/api/data/projects/$id',
  path: '/api/data/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataProjectsDuplicateRoute =
  ApiDataProjectsDuplicateRouteImport.update({
    id: '/api/data/projects/duplicate',
    path: '/api/data/projects/duplicate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDataProjectsRemoveRoute = ApiDataProjectsRemoveRouteImport.update({
  id: '/api/data/projects/remove',
  path: '/api/data/projects/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataProjectsSetPublicRoute =
  ApiDataProjectsSetPublicRouteImport.update({
    id: '/api/data/projects/set-public',
    path: '/api/data/projects/set-public',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/api/compile': typeof ApiCompileRoute
  '/preview/$id': typeof PreviewIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/agents/attachment': typeof ApiAgentsAttachmentRoute
  '/api/agents/delete': typeof ApiAgentsDeleteRoute
  '/api/agents/send': typeof ApiAgentsSendRoute
  '/api/agents/spawn': typeof ApiAgentsSpawnRoute
  '/api/agents/stop': typeof ApiAgentsStopRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/data/tx': typeof ApiDataTxRoute
  '/api/data/projects/$id': typeof ApiDataProjectsIdRoute
  '/api/data/projects/duplicate': typeof ApiDataProjectsDuplicateRoute
  '/api/data/projects/remove': typeof ApiDataProjectsRemoveRoute
  '/api/data/projects/set-public': typeof ApiDataProjectsSetPublicRoute
  '/api/data/projects/': typeof ApiDataProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/api/compile': typeof ApiCompileRoute
  '/preview/$id': typeof PreviewIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/agents/attachment': typeof ApiAgentsAttachmentRoute
  '/api/agents/delete': typeof ApiAgentsDeleteRoute
  '/api/agents/send': typeof ApiAgentsSendRoute
  '/api/agents/spawn': typeof ApiAgentsSpawnRoute
  '/api/agents/stop': typeof ApiAgentsStopRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/data/tx': typeof ApiDataTxRoute
  '/api/data/projects/$id': typeof ApiDataProjectsIdRoute
  '/api/data/projects/duplicate': typeof ApiDataProjectsDuplicateRoute
  '/api/data/projects/remove': typeof ApiDataProjectsRemoveRoute
  '/api/data/projects/set-public': typeof ApiDataProjectsSetPublicRoute
  '/api/data/projects': typeof ApiDataProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/api/compile': typeof ApiCompileRoute
  '/preview/$id': typeof PreviewIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/agents/attachment': typeof ApiAgentsAttachmentRoute
  '/api/agents/delete': typeof ApiAgentsDeleteRoute
  '/api/agents/send': typeof ApiAgentsSendRoute
  '/api/agents/spawn': typeof ApiAgentsSpawnRoute
  '/api/agents/stop': typeof ApiAgentsStopRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/data/tx': typeof ApiDataTxRoute
  '/api/data/projects/$id': typeof ApiDataProjectsIdRoute
  '/api/data/projects/duplicate': typeof ApiDataProjectsDuplicateRoute
  '/api/data/projects/remove': typeof ApiDataProjectsRemoveRoute
  '/api/data/projects/set-public': typeof ApiDataProjectsSetPublicRoute
  '/api/data/projects/': typeof ApiDataProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/api/compile'
    | '/preview/$id'
    | '/projects/$id'
    | '/projects/'
    | '/api/agents/attachment'
    | '/api/agents/delete'
    | '/api/agents/send'
    | '/api/agents/spawn'
    | '/api/agents/stop'
    | '/api/auth/$'
    | '/api/data/tx'
    | '/api/data/projects/$id'
    | '/api/data/projects/duplicate'
    | '/api/data/projects/remove'
    | '/api/data/projects/set-public'
    | '/api/data/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/api/compile'
    | '/preview/$id'
    | '/projects/$id'
    | '/projects'
    | '/api/agents/attachment'
    | '/api/agents/delete'
    | '/api/agents/send'
    | '/api/agents/spawn'
    | '/api/agents/stop'
    | '/api/auth/$'
    | '/api/data/tx'
    | '/api/data/projects/$id'
    | '/api/data/projects/duplicate'
    | '/api/data/projects/remove'
    | '/api/data/projects/set-public'
    | '/api/data/projects'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/api/compile'
    | '/preview/$id'
    | '/projects/$id'
    | '/projects/'
    | '/api/agents/attachment'
    | '/api/agents/delete'
    | '/api/agents/send'
    | '/api/agents/spawn'
    | '/api/agents/stop'
    | '/api/auth/$'
    | '/api/data/tx'
    | '/api/data/projects/$id'
    | '/api/data/projects/duplicate'
    | '/api/data/projects/remove'
    | '/api/data/projects/set-public'
    | '/api/data/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  ApiCompileRoute: typeof ApiCompileRoute
  PreviewIdRoute: typeof PreviewIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiAgentsAttachmentRoute: typeof ApiAgentsAttachmentRoute
  ApiAgentsDeleteRoute: typeof ApiAgentsDeleteRoute
  ApiAgentsSendRoute: typeof ApiAgentsSendRoute
  ApiAgentsSpawnRoute: typeof ApiAgentsSpawnRoute
  ApiAgentsStopRoute: typeof ApiAgentsStopRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDataTxRoute: typeof ApiDataTxRoute
  ApiDataProjectsIdRoute: typeof ApiDataProjectsIdRoute
  ApiDataProjectsDuplicateRoute: typeof ApiDataProjectsDuplicateRoute
  ApiDataProjectsRemoveRoute: typeof ApiDataProjectsRemoveRoute
  ApiDataProjectsSetPublicRoute: typeof ApiDataProjectsSetPublicRoute
  ApiDataProjectsIndexRoute: typeof ApiDataProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compile': {
      id: '/api/compile'
      path: '/api/compile'
      fullPath: '/api/compile'
      preLoaderRoute: typeof ApiCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$id': {
      id: '/preview/$id'
      path: '/preview/$id'
      fullPath: '/preview/$id'
      preLoaderRoute: typeof PreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/attachment': {
      id: '/api/agents/attachment'
      path: '/api/agents/attachment'
      fullPath: '/api/agents/attachment'
      preLoaderRoute: typeof ApiAgentsAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/delete': {
      id: '/api/agents/delete'
      path: '/api/agents/delete'
      fullPath: '/api/agents/delete'
      preLoaderRoute: typeof ApiAgentsDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/send': {
      id: '/api/agents/send'
      path: '/api/agents/send'
      fullPath: '/api/agents/send'
      preLoaderRoute: typeof ApiAgentsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/spawn': {
      id: '/api/agents/spawn'
      path: '/api/agents/spawn'
      fullPath: '/api/agents/spawn'
      preLoaderRoute: typeof ApiAgentsSpawnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/stop': {
      id: '/api/agents/stop'
      path: '/api/agents/stop'
      fullPath: '/api/agents/stop'
      preLoaderRoute: typeof ApiAgentsStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/tx': {
      id: '/api/data/tx'
      path: '/api/data/tx'
      fullPath: '/api/data/tx'
      preLoaderRoute: typeof ApiDataTxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/projects/': {
      id: '/api/data/projects/'
      path: '/api/data/projects'
      fullPath: '/api/data/projects/'
      preLoaderRoute: typeof ApiDataProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/projects/$id': {
      id: '/api/data/projects/$id'
      path: '/api/data/projects/$id'
      fullPath: '/api/data/projects/$id'
      preLoaderRoute: typeof ApiDataProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/projects/duplicate': {
      id: '/api/data/projects/duplicate'
      path: '/api/data/projects/duplicate'
      fullPath: '/api/data/projects/duplicate'
      preLoaderRoute: typeof ApiDataProjectsDuplicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/projects/remove': {
      id: '/api/data/projects/remove'
      path: '/api/data/projects/remove'
      fullPath: '/api/data/projects/remove'
      preLoaderRoute: typeof ApiDataProjectsRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/projects/set-public': {
      id: '/api/data/projects/set-public'
      path: '/api/data/projects/set-public'
      fullPath: '/api/data/projects/set-public'
      preLoaderRoute: typeof ApiDataProjectsSetPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  ApiCompileRoute: ApiCompileRoute,
  PreviewIdRoute: PreviewIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiAgentsAttachmentRoute: ApiAgentsAttachmentRoute,
  ApiAgentsDeleteRoute: ApiAgentsDeleteRoute,
  ApiAgentsSendRoute: ApiAgentsSendRoute,
  ApiAgentsSpawnRoute: ApiAgentsSpawnRoute,
  ApiAgentsStopRoute: ApiAgentsStopRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDataTxRoute: ApiDataTxRoute,
  ApiDataProjectsIdRoute: ApiDataProjectsIdRoute,
  ApiDataProjectsDuplicateRoute: ApiDataProjectsDuplicateRoute,
  ApiDataProjectsRemoveRoute: ApiDataProjectsRemoveRoute,
  ApiDataProjectsSetPublicRoute: ApiDataProjectsSetPublicRoute,
  ApiDataProjectsIndexRoute: ApiDataProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
