/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ApiCompileRouteImport } from './routes/api/compile'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as ApiAgentsSendRouteImport } from './routes/api/agents/send'
import { Route as ApiAgentsSpawnRouteImport } from './routes/api/agents/spawn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompileRoute = ApiCompileRouteImport.update({
  id: '/api/compile',
  path: '/api/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsSendRoute = ApiAgentsSendRouteImport.update({
  id: '/api/agents/send',
  path: '/api/agents/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsSpawnRoute = ApiAgentsSpawnRouteImport.update({
  id: '/api/agents/spawn',
  path: '/api/agents/spawn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/api/compile': typeof ApiCompileRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/agents/send': typeof ApiAgentsSendRoute
  '/api/agents/spawn': typeof ApiAgentsSpawnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/api/compile': typeof ApiCompileRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/agents/send': typeof ApiAgentsSendRoute
  '/api/agents/spawn': typeof ApiAgentsSpawnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/api/compile': typeof ApiCompileRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/agents/send': typeof ApiAgentsSendRoute
  '/api/agents/spawn': typeof ApiAgentsSpawnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/api/compile'
    | '/projects/$id'
    | '/api/agents/send'
    | '/api/agents/spawn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/api/compile'
    | '/projects/$id'
    | '/api/agents/send'
    | '/api/agents/spawn'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/api/compile'
    | '/projects/$id'
    | '/api/agents/send'
    | '/api/agents/spawn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  ApiCompileRoute: typeof ApiCompileRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ApiAgentsSendRoute: typeof ApiAgentsSendRoute
  ApiAgentsSpawnRoute: typeof ApiAgentsSpawnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compile': {
      id: '/api/compile'
      path: '/api/compile'
      fullPath: '/api/compile'
      preLoaderRoute: typeof ApiCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/send': {
      id: '/api/agents/send'
      path: '/api/agents/send'
      fullPath: '/api/agents/send'
      preLoaderRoute: typeof ApiAgentsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/spawn': {
      id: '/api/agents/spawn'
      path: '/api/agents/spawn'
      fullPath: '/api/agents/spawn'
      preLoaderRoute: typeof ApiAgentsSpawnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  ApiCompileRoute: ApiCompileRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ApiAgentsSendRoute: ApiAgentsSendRoute,
  ApiAgentsSpawnRoute: ApiAgentsSpawnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
